# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
