# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20171003_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
