# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('chat', '0009_auto_20171003_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group_id',
        ),
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
