# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20171115_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_msg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
